### ISSUE TITLE
save figure dpi

### ISSUE THREAD

**Issue by MarvelFyy** [LucaCappelletti94/plot_keras_history#3]
Hello, author.

Is there a parameter to save the image into local disc by **custom dpi**?

Looking forward to your reply

**Comment by LucaCappelletti94** [comment]
Hi! I am unsure if I understand what saving an image to disk has to do with its DPI.

Do you mean whether it is possible to increase the image DPIs?

**Comment by MarvelFyy** [comment]
>
Thank you for response!

The follow simple example is  what I mean:
``` 
import matplotlib.pyplot as plt
...
plt.savefig('./figure/figure1.png', dpi=500)
```
where the function's key word argument **dpi**  is what I want to use in your function.

When I use your function, I don't know how  to change the saved figure:

```
from plot_keras_history import  show_history, plot_history

history = model.fit( ... )

plot_history(history.history,  path='./figure/figure1.png') # without the argument dpi

```
All in all, I mean that the figure I use your function ploted is not clear, so I want to set the **dpi** (like matplotlib) to get a more clear figure.

Looking forward to your reply.

**Comment by MarvelFyy** [comment]
> > 
> 
> Thank you for response!
> 
> The follow simple example is what I mean:
> 
> ```
> import matplotlib.pyplot as plt
> ...
> plt.savefig('./figure/figure1.png', dpi=500)
> ```
> 
> where the function's key word argument **dpi** is what I want to use in your function.
> 
> When I use your function, I don't know how to change the saved figure:
> 
> ```
> from plot_keras_history import  show_history, plot_history
> 
> history = model.fit( ... )
> 
> plot_history(history.history,  path='./figure/figure1.png') # without the argument dpi
> ```
> 
> All in all, I mean that the figure I use your function ploted is not clear, so I want to set the **dpi** (like matplotlib) to get a more clear figure.
> 
> Looking forward to your reply.

**Comment by MarvelFyy** [comment]
Hello, author!

I have found the way to set the diffirent dpi for figure by myself!

We can plot the high resolution figure by follows:
```
import matplotlib as mpl
import matplotlib.pyplot as plt
from plot_keras_history import  show_history, plot_history

# here
style = 'fast'
dpi = 500

plt.style.use(style) # set the style what you like
mpl.rcParams['savefig.dpi'] = dpi # save figure dpi
mpl.rcParams['figure.dpi'] = dpi # show figure dpi
plt.rcParams['savefig.dpi'] = dpi
plt.rcParams['figure.dpi'] = dpi 

history = model.fit( ... )

plot_history(history.history,  path='./figure/figure1.png')
```

Anyway，thanks for your reply!

**Comment by LucaCappelletti94** [comment]
Added the parameter.
