### ISSUE TITLE
support-developer package was deleted from pypi and now breaks projects that depends on plot_keras_history

### ISSUE THREAD

**Issue by ryukinix** [LucaCappelletti94/plot_keras_history#4]
Can you release a new version of this lib package without these lines?

https://github.com/LucaCappelletti94/plot_keras_history/blob/1383a30e5659298d749678b75ea1d02f3bd73275/plot_keras_history/__init__.py#L4-L6

Thanks.

**Comment by LucaCappelletti94** [comment]
I thought I had already, thank you for pointing it out.

**Comment by LucaCappelletti94** [comment]
Just gave the package an overall update

**Comment by ryukinix** [comment]
Thank you!

Em seg., 9 de dez. de 2024 07:45, Luca Cappelletti ***@***.***>
escreveu:
